# Generated by Django 4.1.2 on 2022-10-19 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=20)),
                ('university', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('fields', models.CharField(max_length=100)),
                ('abstract', models.CharField(max_length=10000)),
                ('id_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_author.author')),
            ],
        ),
    ]
